#!/bin/bash
# The logic to start up your application should be put in this
# script. The application will work only if it binds to
# $OPENSHIFT_INTERNAL_IP:8080
#PIDFILE=$OPENSHIFT_DATA_DIR/lfs-app/bin/gunicorn.pid
#nohup $OPENSHIFT_DATA_DIR/lfs-app/bin/django run_gunicorn $OPENSHIFT_INTERNAL_IP:$OPENSHIFT_INTERNAL_PORT --pid=$PIDFILE --workers=4 --daemon
nohup $OPENSHIFT_RUNTIME_DIR/lfs-app/bin/django runserver $OPENSHIFT_INTERNAL_IP:$OPENSHIFT_INTERNAL_PORT > $OPENSHIFT_LOG_DIR/server.log 2>&1 &
