#!/bin/bash
# The logic to stop your application should be put in this script.
kill `ps -ef | grep django | grep -v grep | awk '{ print $2 }'` > /dev/null 2>&1
exit 0
#PIDFILE=$OPENSHIFT_DATA_DIR/lfs-app/bin/gunicorn.pid
#kill `cat -- $PIDFILE`
#rm -f -- $PIDFILE
